trigger:
- main

variables:
  # Azure Resource Manager connection name (Service Connection)
  azureSubscription: '61513187-52ef-4879-b2e5-c4118739ccd3'

  # Azure Web App name
  webAppName: 'demo-webappphp'

  # Agent image
  vmImageName: 'ubuntu-latest'

  # Azure environment name
  environmentName: 'demo-webappphp'

  # Folder containing your PHP files (index.php, etc.)
  rootFolder: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        php -v
        ls -la $(rootFolder)
      displayName: 'Check PHP version and list project files'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(rootFolder)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App: $(webAppName)'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppName)
              appType: webAppLinux
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
